const text = [
  `Solar energy materials have properties tailored to meet requirements set by the spectral distribution, angle of incidence, and intensity of the electromagnetic radiation prevailing in our natural surroundings. Specifically, the optimization can be performed with regard to solar irradiation, thermal emission, atmospheric absorption, visible light, and photosynthetic efficiency. Materials for thermal and electrical conversion of solar energy in man-made collectors, as well as for energy-efficient passive design in architecture, are typical examples. This paper reviews solar energy materials with emphasis on the thermal applications of a variety of types. Electrical applications are given a more cursory exposition, the reason being that a systems perspective—rather that a materials perspective—is most fruitful in this case`,
  `In order to improve the accuracy, validity, reliability and reproducibility of reported power conversion efficiencies for solar cells, the journal, Solar Energy Materials and Solar Cells (SOLMAT), wishes to define how power conversion efficiencies should be reported. This expands upon what is specified in our Guide for Authors. This editorial also serves as a guide on how efficiency data should be checked within the reporting laboratory before sending cells or materials for testing at an independent laboratory. The threshold where the accuracy of efficiency values is important to the journal is whenever power conversion efficiencies require external quantum efficiencies (EQE) values above 50% over a large range of wavelengths or when reported power conversion efficiencies exceed 2.5%. Extra care should be taken in submitted manuscripts to document the measurement's quality, relevance and independent verification.`,
  `Transparent conductors (TCs) have a multitude of applications for solar energy utilization and for energy savings, especially in buildings. The largest of these applications, in terms of area, make use of the fact that the TCs have low infrared emittance and hence can be used to improve the thermal properties of modern fenestration. Depending on whether the TCs are reflecting or not in the near infrared pertinent to solar irradiation, the TCs can serve in “solar control” or “low-emittance” windows. Other applications rely on the electrical conductivity of the TCs, which make them useful as current collectors in solar cells and for inserting and extracting electrical charge in electrochromic “smart windows” capable of combining energy efficiency and indoor comfort in buildings. This Review takes a “panoramic” view on TCs and discusses their properties from the perspective of the radiative properties in our ambience. This approach leads naturally to considerations of spectral selectivity, angular selectivity, and temporal variability of TCs, as covered in three subsequent sections. The spectrally selective materials are thin films based on metals (normally gold or titanium nitride) or wide band gap semiconductors with heavy doping (normally based on indium, tin, or zinc). Their applications to energy-efficient windows are covered in detail, experimentally as well as theoretically, and briefer discussions are given applications to solar cells and solar collectors. Photocatalytic properties and super-hydrophilicity are touched upon. Angular selective TCs, for which the angular properties are caused by inclined columnar nanostructures, are then covered. A discussion of TC-like materials with thermochromic and electrochromic properties follows in the final part. Detailed treatments are given for thermochromic materials based on vanadium dioxide and for electrochromic multi-layer structures (incorporating TCs as essential components). The reference list is extensive and aims at giving an easy entrance to the many varied aspects of TCs.`,
  `Although window is the main medium for the lighting of the building, it contributes significantly in the building’s energy consumption, either commercial or residential. In the general frame of a growing world population and consequently of an increasing demand for reducing energy consumption for building needs, the development of appropriate glazing materials towards the maximum reduction of energy losses or gains is a major pre-requisite of modern architecture and thus of intense research in recent years. In this review, new work on insulating, reflecting, electrochromic, thermochromic, photovoltaic, water flow-based and emerging innovative materials is presented in an attempt to reveal the benefits of each glazing category but also the required research needs for future development. High energy savings can be achieved by integrating innovative transparent components in the building envelope. Insulating materials have reached a very low thermal conductivity in their sensible heating and recent complex radiative cooling multi-coatings have proved that temperatures even below the ambient can be reached indoors. Glazing integrated PVs, are among the most promising solutions due to heating and cooling savings in addition to electricity production. Finally, the combination of different panes in double glazing windows can optimize the environmental solar interaction of windows and maximize building energy savings.`,
  `This paper introduces materials for energy efficiency and solar energy utilization and discusses some current trends for basic research and development. Most of the materials involve thin surface coatings. Overviews are given for solar absorber surfaces, transparent infrared reflectors and transparent conductors, large-area chromogenics for transmittance control in “smart windows”, and transparent convection-suppressing materials, whereas solar cell materials are not included. The paper also treats a few examples of specific coatings that are presently being investigated; data are given for angular-selective transmittance through porous Cr films with oblique columnar microstructure, transparent and conducting non-stoichiometric SnO2 films, and chromogenic effects in Li-intercalated VO2 films.`,
  `Direct energy gap materials, e.g. CdTe, CuInSe2, CuInGaSe2, CdSe, ZnP2 and Zn3P2, are the most interesting for thin-film solar cell applications. Among the various methods of preparation of these films, chemical bath deposition and electrodeposition deserve special attention because they have been shown to be inexpensive, low-temperature and non-polluting methods. Based on Pourbaix diagrams of CdS, CdTe, CuInSe2, CdSe, etc., drawn from basic considerations, the best parameters for their electrodeposition are deduced. Theoretical considerations on the chemical-bath deposition of CdS, CdSe and Sb2S3 are also indicated. In particular, the role of the complexing agent and of the ligands in chemical bath deposition quality is discussed, as are the uniformity and stability of the films. The photoelectrochemical, Schottky barrier and heterojunction solar cell properties based on chemically and electrochemically deposited thin films with heteropolyacids are shown. Future trends for chemically and electrochemically deposited polycrystalline thin films are addressed. Results from very recent work done in the improvement of chemically and electrochemically deposited thin films are presented. Significant results obtained on advanced CdS/CdTe, CdS/CIS and CdS/CIGS solar cells developed by industry and by laboratory groups worldwide are indicated. Emerging low cost materials or/and less environmental hazards materials which may introduce solar cells into worldwide market are considered in the conclusion.`,
  `The present work considers hydrogen generation from water using solar energy. The work is focused on the materials-related issues in the development of high-efficiency photo-electrochemical cells (PECs). The property requirements for photo-electrodes, in terms of semiconducting and electrochemical properties and their impact on the performance of PECs, are outlined. Different types of PECs are overviewed and the impact of the PEC structure and materials selection on the conversion efficiency of solar energy are considered.`,
  `Trends in research in the development of high-efficiency PECs are discussed. It is argued that very sophisticated materials engineering must be used for processing the materials that will satisfy the specific requirements for photo-electrodes. An important issue in the processing of these materials is the bulk vs. interface properties at the solid/solid interfaces (e.g., grain boundaries) and solid/liquid interfaces (e.g., electrode/electrolyte interface). Consequently, the development of PECs with the efficiency required for commercialization requires the application of up-to-date materials processing technology.`,
  `According to current predictions, the production of hydrogen will skyrocket by 2010 (Morgan and Sissine, Congressional Research Service, Report for Congress. The Committee for the National Institute for the Environment, Washington, DC, 20006-1401, 28 April 1995). Consequently, seed funding already has been allocated to several national research programs aiming at the development of hydrogen technology. The countries having access to this PEC technology are likely to form the OPEC of the future.`,
  `The querySelector() method returns the first element that matches a CSS selector. To return all matches (not only the first), use the querySelectorAll() instead. Both querySelector() and querySelectorAll() throw a SYNTAX_ERR exception if the selector(s) is invalid.`,
  `The getElementById() method returns an element with a specified value.The getElementById() method returns null if the element does not exist. The getElementById() method is one of the most common methods in the HTML DOM. It is used almost every time you want to read or edit an HTML element.`,
  `The setAttribute() method sets a new value to an attribute. If the attribute does not exist, it is created first.`,
  `The appendChild() method appends a node (element) as the last child of an element.`,
  `The addEventListener() method attaches an event handler to an element.`,
  `The removeEventListener() method removes an event handler from an element.`,
  `The innerText property sets or returns the text content of an element.`,
  `The innerHTML property sets or returns the HTML content (inner HTML) of an element.`,
];

const input = document.querySelector('#amount');
const btn = document.querySelector('.btn');
const result = document.querySelector('.lorem-text');

btn.addEventListener('click', e => {
  e.preventDefault();
  //   console.log('click');
  let value = input.value;
  if (value < 0 || value > 17 || isNaN(value)) {
    alert('Enter a value between 1-17');
  } else {
    let temp = text
      .slice(0, value)
      .map(v => `<p>${v}</p>`)
      .join('');
    // temp = temp.map(v => `<p>${v}</p>`).join('');
    result.innerHTML = temp;
  }
});
window.onload = () => {
  input.focus();
};
